data:
  raw_dir: data/raw/
  processed_dir: data/processed/
  labels_file: data/labels.csv
model:
  input_shape: [224, 224, 1]
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
output:
  model_dir: outputs/models/
  log_dir: outputs/logs/
  result_dir: outputs/results/
