# config.yaml
data:
  raw_path: "data/raw"
  processed_path: "data/processed"
  labels_file: "data/labels.csv"
  img_size: 224
  batch_size: 32
  test_size: 0.2
  random_state: 42

model:
  architecture: "custom_cnn"
  learning_rate: 0.001
  epochs: 30
  early_stopping_patience: 5

paths:
  model_save: "outputs/models/best_model.h5"
  logs: "outputs/logs/"
  results: "outputs/results/"
